image:
  repository: ghcr.io/dani025a/hello-service
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 3001

env:
  - name: NODE_ENV
    value: 'production'
  - name: PORT
    value: '3001'
  - name: RABBITMQ_URL
    value: 'amqp://guest:guest@rabbitmq.default.svc.cluster.local:5672'

resources: {}
