apiVersion: v1
kind: Service
metadata:
  name: hello
spec:
  type: { { .Values.service.type } }
  selector:
    app: hello-service
  ports:
    - port: { { .Values.service.port } }
      targetPort: { { .Values.service.targetPort } }
