name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # PNPM version comes from package.json "packageManager"
      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build all
        run: pnpm -r build

      # Enable Buildx (container driver) so cache export type=gha works
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Docker login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Force owner to lowercase for GHCR tags
      - name: Compute lowercase owner
        run: echo "REPO_LOWER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build + Push hello-service
        uses: docker/build-push-action@v6
        with:
          context: .
          file: services/hello-service/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.REPO_LOWER }}/hello-service:${{ github.sha }}
            ghcr.io/${{ env.REPO_LOWER }}/hello-service:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
