@'
name: ci

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Use pnpm from package.json "packageManager" (removes version clash)
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Cache pnpm store
        id: pnpm-cache
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build all
        run: pnpm -r build

      - name: Docker login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image vars
        id: vars
        run: echo "IMAGE=ghcr.io/${{ github.repository_owner }}/hello-service" >> $GITHUB_OUTPUT

      - name: Build + Push hello-service
        uses: docker/build-push-action@v6
        with:
          context: .
          file: services/hello-service/Dockerfile
          push: true
          tags: |
            ${{ steps.vars.outputs.IMAGE }}:${{ github.sha }}
            ${{ steps.vars.outputs.IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
'@ | Set-Content .github\workflows\ci.yml -Encoding utf8

git add .github/workflows/ci.yml
git commit -m "ci: fix pnpm version conflict by using packageManager version"
git pull --rebase origin main
git push origin main
