name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Use pnpm from package.json "packageManager" (no version duplication)
      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build all
        run: pnpm -r build

      - name: Docker login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build + Push hello-service
        uses: docker/build-push-action@v6
        with:
          context: .
          file: services/hello-service/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/hello-service:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/hello-service:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
